- name: Configure EC2
  hosts: web
  become: true
  tasks:
    - name: Install Apache
      yum:
        name: apache2
        state: present

    - name: Start Apache
      service:
        name: apache2
        state: started

    - name: Enable Apache on boot
      service:
        name: apache2
        enabled: yes

    - name: Deploy Web Page
      copy:
        content: "<h1>Terraform + Jenkins + Ansible Deployment Successful!</h1>"
        dest: /var/www/html/index.html

